### ISSUE TITLE
Non-link navigation items unindented on docs page

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/multipass.run#100]
In https://multipass.run/docs

For links in navigation we have
```css
padding-left: 1.5rem;
```

But not for plain text (think grouping under a common topic), which gets undented:

![image](https://user-images.githubusercontent.com/231077/83905157-7bdd7a00-a761-11ea-9117-e236920879dd.png)

**Comment by anthonydillon** [comment]
Resolved by making the non-link title a heading:
![image](https://user-images.githubusercontent.com/1413534/84051820-92751280-a9a7-11ea-9512-2042786826e0.png)
