### ISSUE TITLE
Incorrect information regarding the default version installed

### ISSUE THREAD

**Issue by AntonOfTheWoods** [canonical-web-and-design/multipass.run#105]
We are now in July, more than 2 months after the official release of 20.04. https://multipass.run/ and https://snapcraft.io/multipass both report that "Launch an instance (by default you get the current Ubuntu LTS)" but I just did that and got a 18.04. Is there something I'm missing?

**Comment by SirSamTumless** [comment]
@Saviq Would you mind looking into this?

**Comment by Saviq** [comment]
> We are now in July, more than 2 months after the official release of 20.04. https://multipass.run/ and https://snapcraft.io/multipass both report that "Launch an instance (by default you get the current Ubuntu LTS)" but I just did that and got a 18.04. Is there something I'm missing?

Hi @AntonOfTheWoods the "default" image doesn't switch until the first point release (20.04.1 release [is planned on August 6th](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule)). You could say it's the Ubuntu Foundations' team decision when the "default" Ubuntu image changes.

**Comment by AntonOfTheWoods** [comment]
Thanks @Saviq . I may be particularly anal retentive but I must confess I wasn't expecting that answer.  If I'm the only one bothered by it then fine. It is certainly but a tiny blemish on the awesomeness that is `multipass`, so definitely not a biggie!
