### ISSUE TITLE
Documentation suggests using Homebrew to install on macOS

### ISSUE THREAD

**Issue by sneak** [canonical-web-and-design/multipass.run#120]
Homebrew is spyware that transmits the user's activities to Google without consent.

Please do not recommend spyware.

**Comment by SirSamTumless** [comment]
@Saviq please could you respond to this.

**Comment by cassiocassio** [comment]
HOMEBREW_NO_ANALYTICS=1 

context to that debate: https://news.ycombinator.com/item?id=11566720

**Comment by sneak** [comment]
Yes, if you are unaware of these commands or do not run them, it transmits your activity data automatically to Google, along with a UUID, without consent.

**Comment by anthonydillon** [comment]
I have added a link this issue to the discourse topic for further exposure. https://discourse.ubuntu.com/t/installing-multipass-on-macos/8329/9

**Comment by pmahnke** [comment]
closing as it is being looked at in the discource topic, not a website issue per se.
