### ISSUE TITLE
./run failing on mac 

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/multipass.run#147]
Can't run the site locally to work on it - I've tried `./run clean` but still getting the same error. 

`An unexpected error occurred: "/home/shared/.cache/yarn/v6/npm-meow-8.1.0-0fcaa267e35e4d58584b8205923df6021ddcc7ba-integrity/node_modules/meow/.yarn-metadata.json: Unexpected end of JSON input".`

**Comment by anthonydillon** [comment]
@bethcollins92 could you provide the entire output please?

**Comment by bethcollins92** [comment]
> @bethcollins92 could you provide the entire output please?

@anthonydillon sure: 
![image](https://user-images.githubusercontent.com/58959073/110462241-53a3f280-80c8-11eb-8bbd-c52baa6378d8.png)

**Comment by bethcollins92** [comment]
![image](https://user-images.githubusercontent.com/58959073/110463512-ea24e380-80c9-11eb-9861-e4861f6d4914.png)

**Comment by bethcollins92** [comment]
![image](https://user-images.githubusercontent.com/58959073/110464032-8c44cb80-80ca-11eb-8e8d-5f89e24a43a5.png)

**Comment by anthonydillon** [comment]
@nottrobin is there any way to run yarn commands in the docker file without `./run` trying to install first?

**Comment by nottrobin** [comment]
Oh that's a pain. I'm confused that `./run exec` doesn't work, I didn't think that would normally try to install...

What happens if you type `./run exec bash`?

**Comment by bethcollins92** [comment]
![image](https://user-images.githubusercontent.com/58959073/110474437-915c4780-80d7-11eb-8dae-6e82f4b2ce81.png)

**Comment by bethcollins92** [comment]
> Huh that sucks. Did you try `./run clean` already?

Yeh, tried that already

**Comment by bethcollins92** [comment]
And we're in! 🥳 Thanks for the help @anthonydillon and @nottrobin

**Comment by anthonydillon** [comment]
No prob, @bethcollins92 what was the solution in the end?

**Comment by bethcollins92** [comment]
@anthonydillon `./run clean-cache`
