### ISSUE TITLE
can't find link to download the server iso

### ISSUE THREAD

**Issue by Sturmey66** [canonical-web-and-design/multipass.run#150]
Went to ubuntu.com/download/server and wound up here. Nowhere was there a link to download a version of the ubuntu server. WTF?

**Comment by SirSamTumless** [comment]
Thanks for flagging this issue - could you please click "option 2" and select "Download Ubuntu Server 20.04.2 LTS".

**Comment by Sturmey66** [comment]
I don't see option #2 it just says get multipass.

**Comment by carkod** [comment]
Hi @Sturmey66 ,

What @SirSamTumless is referring to is this:

<img width="1440" alt="Screenshot 2021-03-11 at 12 30 03" src="https://user-images.githubusercontent.com/14939793/110787750-a666e100-8265-11eb-8ffd-1540c37d97f2.png">

**Comment by Sturmey66** [comment]
You need a better web designer. That's not obvious to everyone.If I'm on a "download page and there is a big green button, I'm going to click it. Some gray on grey link to get to the actual download page isn't that visible. Why is the download page not actually the download page? On Mar 11, 2021 06:31, Carlos Wu ***@***.***> wrote:
Hi @Sturmey66 ,
What @SirSamTumless is referring to is this:

**Comment by g1964j** [comment]
Du répit c est mieux pour l instant de comprendre.

**Comment by carkod** [comment]
Issue seems to be resolved, please reopen if need more help.
