### ISSUE TITLE
ubuntu for MacBook Pro + Apple M1

### ISSUE THREAD

**Issue by Biznaka** [canonical-web-and-design/multipass.run#154]
Para cuando una version de ubuntu ARM para el MacBook Pro Apple M1???
Gracias.

For when a version of ubuntu ARM for the MacBook Pro Apple M1 ???
Thanks.

**Comment by cassiocassio** [comment]
I see that there's a lot of wider community interest in this - and a lot of upstream work to enable -any- distribution to be GPU performant - see https://asahilinux.org/about/

**Comment by anthonydillon** [comment]
@Biznaka thank you for your interest in this field. This is the project for the ubuntu.com project. We cannot promise to provide this. If you could report a bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question as a topic on https://discourse.ubuntu.com/c/support-help-requests and you should receive a quick response.
