### ISSUE TITLE
Multipass does not play well with VirtualBox on MacOS

### ISSUE THREAD

**Issue by Wee-Free-Scot** [canonical-web-and-design/multipass.run#195]
I followed the instructions here:
https://multipass.run/docs/using-virtualbox-in-multipass-macos
and here:
https://multipass.run/docs/installing-on-macos
but multipass refuses to launch anything, claiming that:
```
launch failed: Conversion of image to VDI failed (Process returned exit code: 1) with the following output:
qemu-img: Unknown file format 'vdi'
```

I have updated VirtualBox on my Mac to the latest version earlier today.

I have tried the download-a-package route and (separately) the Homebrew route.

I have tried brew installing hyper kit before brew installing multipass.

I have tried running everything using sudo.

The problem seems to be the instruction:
```
$ sudo multipass set local.driver=virtualbox
```

Once this command has been executed, multipass is useless.

I instead executed this command to undo the one above:
```
$ sudo multipass set local.driver=hyperkit
```

Using hyperkit seems to work, but using virtualbox does not.

**Comment by bethcollins92** [comment]
@Saviq - could you take a look at this please?

**Comment by Saviq** [comment]
@bethcollins92 can you please transfer this to canonical/multipass?

**Comment by Saviq** [comment]
In any case, I can confirm the problem and we're working on a fix.

**Comment by bethcollins92** [comment]
> @bethcollins92 can you please transfer this to canonical/multipass?

Need to try and figure out how to move the issue to a different repo as it's not in the same organisation - (we use `canonical-web-and-design`). Do you know if this is possible?

**Comment by Saviq** [comment]
@bethcollins92 I've filed it under canonical/multipass#2322, feel free to close this.

**Comment by bethcollins92** [comment]
> @bethcollins92 I've filed it under [canonical/multipass#2322](https://github.com/canonical/multipass/issues/2322), feel free to close this.

Hooray - thank you!
