### ISSUE TITLE
Navigation links render differently depending on whether they are first level or not

### ISSUE THREAD

**Issue by ricab** [canonical-web-and-design/multipass.run#232]
When hovering over links in the navigation pane in https://multipass.run/docs, the links in the first level render in the usual blue+underline, while links in sublevels render with a grey background highlight.

---

![blue_link](https://user-images.githubusercontent.com/6698114/158376103-dc4bec9f-81f1-4dc8-a61d-2c3518932c38.png)
![grey_link](https://user-images.githubusercontent.com/6698114/158376107-a9494bd5-7848-4700-b906-6c728e6cef5e.png)

**Comment by anthonydillon** [comment]
I have updated the link values to start from 1. Which by design for the docs navigation. If you use 0 it should not contain a link and should be used to title a section of the navigation.
