### ISSUE TITLE
Expand/collapse nodes in the navigation tree

### ISSUE THREAD

**Issue by ricab** [canonical-web-and-design/multipass.run#234]
It would be really nice to be able to expand and collapse nodes in the tree of links that is shown in the navigation pane. That would allow visualizing the overall Diátaxis structure while keeping the detail of deeper nodes in the tree of links.

**Comment by ricab** [comment]
Without this capability, we're being advised to remove the "level" from deeper nodes in the tree, so that they don't show up in the navigation pane and the 4-category split is apparent (without scrolling).

**Comment by anthonydillon** [comment]
This pattern is currently in [consideration in Vanilla](https://github.com/canonical-web-and-design/vanilla-framework/issues/4122). @EvilDMP do you agree this is the right path forward for docs navigation?

**Comment by evildmp** [comment]
I certainly do!

**Comment by cristinadresch** [comment]
Closing this one for, please subscribe to the vanilla issue so you can keep track of progress there. Thanks
