### ISSUE TITLE
important keyword missing in cheatsheet, as offered on multipass site

### ISSUE THREAD

**Issue by carehart** [canonical-web-and-design/multipass.run#235]
In the cheatsheet [offered on the site](https://assets.ubuntu.com/v1/f401c3f4-Ubuntu_Server_CLI_pro_tips_2020-04.pdf) as "_Ubuntu Server CLI pro tips_", the two-page PDF has a section on the first page showing a group of 3 commands for "_Which package provides this file?_". The last of the 3 shows `apt-file <filename or command>`, but that just causes display of the command's help (without pointing out what mistake was made).

Reading the help, we can see that the issue is that the command as offered should have used a "find" keyword, as in:

`apt-file find <filename or command>`

Perhaps there was a time in the past when that was a default, but since I experienced it in finding the cheatsheet today (on the front page at multipass.run) and in following the steps, I wanted to pass it along for you to consider fixing, for the sake of future readers. Thanks for the cheatsheet, otherwise.

**Comment by carkod** [comment]
Duplicated and also completed https://github.com/canonical-web-and-design/web-squad/issues/5176
