### ISSUE TITLE
Missing information on multipass.run 

### ISSUE THREAD

**Issue by schoebu** [canonical-web-and-design/multipass.run#242]
i miss informations about the available distribution versions like 22.04, unity in multipass in macos with M1.

**Comment by carkod** [comment]
Hi @schoebu can you post your request for more info in the discourse forum? https://discourse.ubuntu.com/t/multipass-documentation/8294?_ga=2.103629952.1424813834.1651057789-851870103.1651057789

You will have better chances there to obtain more info, as this is simply the website repo.
Thank you.
