### ISSUE TITLE
--memory is now -mem, examples should be updated

### ISSUE THREAD

**Issue by ald8** [canonical-web-and-design/multipass.run#254]
https://multipass.run/docs/create-an-instance#heading--create-an-instance-with-custom-cpu-number-disk-and-ram should be updated with -- mem instead of --memory

[Create an instance with custom CPU number, disk, and RAM](https://multipass.run/docs/create-an-instance#heading--create-an-instance-with-custom-cpu-number-disk-and-ram)

    See also: [launch ... --cpus ... --disk ... --mem ...](https://multipass.run/docs/launch-command)

A custom number of CPUs, disk and RAM size is specified using the following arguments:

$ multipass launch --cpus 4 --disk 20G --mem 8G
Launched: giving-catfish

**Comment by Saviq** [comment]
@townsend2010 :point_up_2:

**Comment by townsend2010** [comment]
Hey @ald8,

Thanks for pointing this out!  I've fixed this.  FYI, we have plans to allow `--memory` for the option in Multipass, but we haven't put it in yet :slightly_smiling_face: 

@sowasred2012, this can be closed, thanks!

**Comment by sowasred2012** [comment]
Perfect, thanks @townsend2010 @Saviq - closing.
