### ISSUE TITLE
Similar install instructions blocks as in snapcraft.io

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/multipass.run#27]
Would be good to have a consistent element for install instructions between snapcraft.io and multipass.run.

The current ones on multipass.run are oversized.

![image](https://user-images.githubusercontent.com/8167677/57027506-734c7300-6c34-11e9-9099-3f3af52cd9eb.png)

![image](https://user-images.githubusercontent.com/8167677/57027520-7c3d4480-6c34-11e9-8de6-e0328d0b8b3f.png)

**Comment by anasereijo** [comment]
@spencerbygraves is this something you want to look at?

**Comment by anthonydillon** [comment]
@spencerbygraves heads up, there has been a request to update this section in the [copy doc](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit).

**Comment by spencerbygraves** [comment]
@anthonydillon I guess we can close this then.
