### ISSUE TITLE
Incorrect Windows / macOS download links

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/multipass.run#38]
Hey,

Mark just noticed that 0.6.1 is linked to from [multipass.run](https://multipass.run/) for Windows and macOS, and the latest release in fact [is 0.7.0](https://github.com/CanonicalLtd/multipass/releases).

Something's gone wrong with the client-side version detection…

**Comment by Saviq** [comment]
Hey, this is still not deployed as far I can see?

**Comment by anthonydillon** [comment]
@Saviq sorry about that, Its live now.
