### ISSUE TITLE
Add HTTPS certs for {staging.}multipass.io

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/multipass.run#5]
Ask IS to create HTTPS certs for staging.multipass.io and multipass.io, and put them in Kubernetes as secrets.

**Comment by nottrobin** [comment]
Ask IS to create HTTPS certs for staging.multipass.io and multipass.io, and put them in Kubernetes as secrets.

**Comment by nottrobin** [comment]
Blocked until we [decide and procure the domain](https://github.com/canonical-websites/multipass.io/issues/6)

**Comment by nottrobin** [comment]
[RT #113112: Add HTTPS certs for {staging.}multipass.run as Kubernetes secrets](https://portal.admin.canonical.com/C113112) created

**Comment by tbille** [comment]
Ticket resolved
