### ISSUE TITLE
Wrong version selected for install

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/multipass.run#67]
GitHub's API is ordering the releases in https://api.github.com/repositories/114128199/releases by draft creation date.

So if a draft for X was created before Y, even if they are released in reverse, the website would pick up X for download.

With the advent of `/static/latest-release.json`, we could read that instead, even if that's a temporary measure?

**Comment by nottrobin** [comment]
@Saviq sorry where is the wrong version selected? What are we currently doing that consumes the releases API? I wasn't aware that we were dynamically displaying the version anywhere on the website. Did I miss it?

**Comment by Saviq** [comment]
Hey @nottrobin, sorry - the links at https://multipass.run/#install point directly at the installers, with [/static/js/installversion.js](https://github.com/canonical-web-and-design/multipass.run/blob/master/static/js/installversion.js) determining the links.

I fixed it for now by reordering the releases on GitHub.

**Comment by nottrobin** [comment]
@Saviq do you mind if we keep that as the solution as that for now? As mentioned in https://github.com/canonical-web-and-design/multipass.run/pull/64, this whole solution should really be based around a real packaging system, so I'm loathe to build in more dependency on `/static/latest-release.json`. If this works for now, let's leave it based off GitHub releases.

I suspect the GitHub releases API also lets you pick the latest *stable* release as well, if we just tweaked it a bit. That would be a better solution I think.
