### ISSUE TITLE
Broken `target=_blank` icons

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/multipass.run#76]
![obraz](https://user-images.githubusercontent.com/231077/74852909-7dfc0400-533d-11ea-8e06-380166ff07bb.png)
![obraz](https://user-images.githubusercontent.com/231077/74852936-85bba880-533d-11ea-8f6d-67c4b0b1f7af.png)

https://github.com/canonical-web-and-design/multipass.run/issues/75#issue-565743926 also shows a similar problem on earlier macOS?

**Comment by anthonydillon** [comment]
This is a known issue from Vanilla framework: https://github.com/canonical-web-and-design/vanilla-framework/issues/2728.
